# Generated by Django 3.2.13 on 2022-08-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonimo', max_length=200),
        ),
    ]
